config/routes.rb
Rails.application.routes.draw do



  resources :mains 
  resources :shippers
  resources :carriers
  resources :endadds
  resources :startadds
  resources :bids
  resources :endaddresses
  resources :startaddresses
  resources :jobs do
  	member do
    	get :post
  	end
  	member do
    	get :bid
  	end  	
  end
  devise_for :users do
		  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
		end
  resources :users, :only => [:show]
  resources :posts
  resources :conversations, only: [:index, :show, :destroy] do
		  member do
		    post :reply
		  end
		  member do
		    post :restore
		  end	
		 collection do
	    	delete :empty_trash
	  	end  
	  	member do
	    	post :mark_as_read
	  	end
	end
  resources :messages, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "mains#index"
end

app/models/startadd.rb
class Startadd < ApplicationRecord
  belongs_to :job
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode 
end

app/controllers/startadds_controller.rb
class StartaddsController < ApplicationController
  before_action :set_startadd, only: [:show, :edit, :update, :destroy]

  # GET /startadds
  # GET /startadds.json
  def index
    @startadds = Startadd.all
  end

  # GET /startadds/1
  # GET /startadds/1.json
  def show
  end

  # GET /startadds/new
  def new
    @startadd = Startadd.new
  end

  # GET /startadds/1/edit
  def edit
  end

  # POST /startadds
  # POST /startadds.json
  def create
    @startadd = Startadd.new(startadd_params)

    respond_to do |format|
      if @startadd.save
        format.html { redirect_to @startadd, notice: 'Startadd was successfully created.' }
        format.json { render :show, status: :created, location: @startadd }
      else
        format.html { render :new }
        format.json { render json: @startadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startadds/1
  # PATCH/PUT /startadds/1.json
  def update
    respond_to do |format|
      if @startadd.update(startadd_params)
        format.html { redirect_to @startadd, notice: 'Startadd was successfully updated.' }
        format.json { render :show, status: :ok, location: @startadd }
      else
        format.html { render :edit }
        format.json { render json: @startadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startadds/1
  # DELETE /startadds/1.json
  def destroy
    @startadd.destroy
    respond_to do |format|
      format.html { redirect_to startadds_url, notice: 'Startadd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startadd
      @startadd = Startadd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startadd_params
      params.require(:startadd).permit(:address, :lat, :lng, :job_id)
    end
end

app/helpers/startadds_helper.rb
module StartaddsHelper
end

app/views/startadds/_form.html.erb
<%= form_for(@startadd, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @startadd.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@startadd.errors.count, "error") %> prohibited this startadd from being saved:</h4>

      <ul>
      <% @startadd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lng, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lng, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :job, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/startadds/edit.html.erb
<div class="page-header">
  <%= link_to startadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @startadd, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing startadd</h1>
</div>

<%= render 'form' %>

app/views/startadds/index.html.erb
<div class="page-header">
  <%= link_to new_startadd_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Startadd
  <% end %>
  <h1>Listing startadds</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Address</th>
            <th>Lat</th>
            <th>Lng</th>
            <th>Job</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @startadds) do |startadd| %>
            <td><%= startadd.address %></td>
            <td><%= startadd.lat %></td>
            <td><%= startadd.lng %></td>
            <td><%= startadd.job %></td>
            <td><%= link_to 'Show', startadd %></td>
        <td><%= link_to 'Edit', edit_startadd_path(startadd) %></td>
        <td><%= link_to 'Destroy', startadd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/startadds/new.html.erb
<div class="page-header">
  <%= link_to startadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New startadd</h1>
</div>

<%= render 'form' %>

app/views/startadds/show.html.erb
<div class="page-header">
  <%= link_to startadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_startadd_path(@startadd), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show startadd</h1>
</div>

<dl class="dl-horizontal">
  <dt>Address:</dt>
  <dd><%= @startadd.address %></dd>

  <dt>Lat:</dt>
  <dd><%= @startadd.lat %></dd>

  <dt>Lng:</dt>
  <dd><%= @startadd.lng %></dd>

  <dt>Job:</dt>
  <dd><%= @startadd.job %></dd>

</dl>