config/routes.rb
Rails.application.routes.draw do



  resources :mains 
  resources :shippers
  resources :carriers
  resources :endadds
  resources :startadds
  resources :bids
  resources :endaddresses
  resources :startaddresses
  resources :jobs do
  	member do
    	get :post
  	end
  	member do
    	get :bid
  	end  	
  end
  devise_for :users do
		  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
		end
  resources :users, :only => [:show]
  resources :posts
  resources :conversations, only: [:index, :show, :destroy] do
		  member do
		    post :reply
		  end
		  member do
		    post :restore
		  end	
		 collection do
	    	delete :empty_trash
	  	end  
	  	member do
	    	post :mark_as_read
	  	end
	end
  resources :messages, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "mains#index"
end

app/models/endadd.rb
class Endadd < ApplicationRecord
  belongs_to :job
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode 
end

app/controllers/endadds_controller.rb
class EndaddsController < ApplicationController
  before_action :set_endadd, only: [:show, :edit, :update, :destroy]

  # GET /endadds
  # GET /endadds.json
  def index
    @endadds = Endadd.all
  end

  # GET /endadds/1
  # GET /endadds/1.json
  def show
  end

  # GET /endadds/new
  def new
    @endadd = Endadd.new
  end

  # GET /endadds/1/edit
  def edit
  end

  # POST /endadds
  # POST /endadds.json
  def create
    @endadd = Endadd.new(endadd_params)

    respond_to do |format|
      if @endadd.save
        format.html { redirect_to @endadd, notice: 'Endadd was successfully created.' }
        format.json { render :show, status: :created, location: @endadd }
      else
        format.html { render :new }
        format.json { render json: @endadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endadds/1
  # PATCH/PUT /endadds/1.json
  def update
    respond_to do |format|
      if @endadd.update(endadd_params)
        format.html { redirect_to @endadd, notice: 'Endadd was successfully updated.' }
        format.json { render :show, status: :ok, location: @endadd }
      else
        format.html { render :edit }
        format.json { render json: @endadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endadds/1
  # DELETE /endadds/1.json
  def destroy
    @endadd.destroy
    respond_to do |format|
      format.html { redirect_to endadds_url, notice: 'Endadd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endadd
      @endadd = Endadd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endadd_params
      params.require(:endadd).permit(:address, :lat, :lng, :job_id)
    end
end

app/helpers/endadds_helper.rb
module EndaddsHelper
end

app/views/endadds/_form.html.erb
<%= form_for(@endadd, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @endadd.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@endadd.errors.count, "error") %> prohibited this endadd from being saved:</h4>

      <ul>
      <% @endadd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lng, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lng, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :job, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/endadds/edit.html.erb
<div class="page-header">
  <%= link_to endadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @endadd, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing endadd</h1>
</div>

<%= render 'form' %>

app/views/endadds/index.html.erb
<div class="page-header">
  <%= link_to new_endadd_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Endadd
  <% end %>
  <h1>Listing endadds</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Address</th>
            <th>Lat</th>
            <th>Lng</th>
            <th>Job</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @endadds) do |endadd| %>
            <td><%= endadd.address %></td>
            <td><%= endadd.lat %></td>
            <td><%= endadd.lng %></td>
            <td><%= endadd.job %></td>
            <td><%= link_to 'Show', endadd %></td>
        <td><%= link_to 'Edit', edit_endadd_path(endadd) %></td>
        <td><%= link_to 'Destroy', endadd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/endadds/new.html.erb
<div class="page-header">
  <%= link_to endadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New endadd</h1>
</div>

<%= render 'form' %>

app/views/endadds/show.html.erb
<div class="page-header">
  <%= link_to endadds_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_endadd_path(@endadd), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show endadd</h1>
</div>

<dl class="dl-horizontal">
  <dt>Address:</dt>
  <dd><%= @endadd.address %></dd>

  <dt>Lat:</dt>
  <dd><%= @endadd.lat %></dd>

  <dt>Lng:</dt>
  <dd><%= @endadd.lng %></dd>

  <dt>Job:</dt>
  <dd><%= @endadd.job %></dd>

</dl>