config/routes.rb
Rails.application.routes.draw do



  resources :mains 
  resources :shippers
  resources :carriers
  resources :endadds
  resources :startadds
  resources :bids
  resources :endaddresses
  resources :startaddresses
  resources :jobs do
  	member do
    	get :post
  	end
  	member do
    	get :bid
  	end  	
  end
  devise_for :users do
		  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
		end
  resources :users, :only => [:show]
  resources :posts
  resources :conversations, only: [:index, :show, :destroy] do
		  member do
		    post :reply
		  end
		  member do
		    post :restore
		  end	
		 collection do
	    	delete :empty_trash
	  	end  
	  	member do
	    	post :mark_as_read
	  	end
	end
  resources :messages, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "mains#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_messageable
  has_many :jobs
  has_many :posts
  has_many :bids
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

enum role: [:carrier, :shipper]         


def mailboxer_email(object)
  email
end
         
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
	@users = User.all  	
  end

	def show
		@user = User.find(params[:id])
	end

	def carrier
		@carrier = User.where(role: "carrier")
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-12 lead">Profile<hr></div>
          </div>
          <div class="row">
      <div class="col-sm-4 text-center">
              <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
              display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
            </div>
            <div class="col-sm-8">
              <div class="row">
                <div class="col-sm-12">
                  <h1 class="only-bottom-margin"><%= @user.name %></h1>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <span class="text-muted">Email:</span> <%= @user.email %><br>
                  <span class="text-muted">Phone Number:</span> <%= @user.phone %><br>
                  <small class="text-muted">Member Since: <%= @user.created_at.strftime("%D") %></small>
                </div>
                <div class="col-sm-6">
                  <div class="activity-mini">
                     Company: <%= @user.company %>
                  </div>
                  <div class="activity-mini">
                    Account: <%= @user.role %>
                  </div>
                </div>
              </div>
            </div>
          </div>
</div></div>
<% if @user.id == current_user.id then %>
<%= link_to "Edit Profile", edit_user_registration_path, :class => "btn btn-default" %>
<% else end %>
<br><br>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 button-wrapper">
        <%= link_to "Post Job", new_job_path, class: "btn btn-lg btn-block btn-default" %>   </div>
    <div class="col-md-4 button-wrapper">
        <%= link_to "Browse Jobs", jobs_path, class: "btn btn-lg btn-block btn-primary" %>
    </div>
    <div class="col-md-4 button-wrapper">
<% if @user.role = "shipper" %>
  <%= link_to "See Carriers", carriers_path, class: "btn btn-lg btn-block btn-success" %>
<%end%>
    </div>
  </div>
</div>

<hr />
<%=  %>
<br> <br>
<%=  %>

<br><br>





<br><br>
<hr />
<h3>Loads Posted by <%=@user.company%></h3>
<div class="table-responsive">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= "Status" %></th>
      <th><%= "Listed" %></th>
      <th><%= "Title" %></th>
      <th><%= "Starting Address" %></th>
      <th><%= "Pickup Time "%></th>
      <th><%= "End Address" %></th>
      <th><%= "Dropoff Time" %></th>
      <th><%= "Price" %></th>
      <% if current_user.id == @user.id %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <% @user.jobs.each do |job| %>
      <tr>
        <td><%= job.status %></td>
        <td><%= job.created_at.strftime("%b %d, %Y - %I:%M %p") %></td>
        <td><%= link_to job.title, job_path(job) %></td>
        <td><%= number_to_currency(job.price, unit: "$") %></td>
        <td><%= job.startad %></td>
        <td><%= job.pickuptime.strftime("%b %d, %Y - %I:%M %p") %></td>
        <td><%= job.endad %></td>
        <td><%= job.dropofftime.strftime("%b %d, %Y - %I:%M %p") %></td>
        <td><%= number_to_currency(job.price, unit: "$") %></td>
        <% if current_user.id == @user.id then %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/sign_in.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>